numastat: Update system hugepages memory info from sysfs/node/hugepages directory
numactl/numactl pull request #157
Opened 2022-12-12 06:43 UTC by luochenglcs

`numastat -m` gets hugepages memory just from /sys/devices/system/node/node$/meminfo, it is not the entire hugepages memory of the system, just the default huge page.

Update the entire hugepages memory information from the /sys/devices/system/node/node$/hugepages directory.

#152

2022-12-14 08:57 UTC, andikleen requested changes

2022-12-14 08:57 UTC, andikleen commented on numastat.c
> +                fgets(buf, SMALL_BUF_SIZE, fs);
Missing fclose

2022-12-14 08:57 UTC, andikleen commented on numastat.c
> +                        continue;
Should check if it's really node*

2022-12-14 08:57 UTC, andikleen commented on numastat.c
> +                printf("opendir[%s] error\n", top_path);
The error outputs should all use stderr

2022-12-15 01:29 UTC, luochenglcs commented
@andikleen Please review again.

2022-12-15 12:45 UTC, merged

2022-12-15 12:46 UTC, andikleen commented
Thanks!