libnuma: add numa_set_mempolicy_home_node API
numactl/numactl pull request #211
Opened 2024-01-31 08:25 UTC by luochenglcs

add numa_set_mempolicy_home_node to set home_node for mbind or preferred_many policy.

link: https://lore.kernel.org/all/20211202123810.267175-3-aneesh.kumar@linux.ibm.com/T/#u

2024-01-31 13:02 UTC, andikleen requested changes
Can you move the mmap check with caching into has_home_node()
numa_set_mempolicy_home_node doesn't need it because it can just handle the error (EINVAL probably)

2024-02-01 02:01 UTC, luochenglcs commented
> Can you move the mmap check with caching into has_home_node() numa_set_mempolicy_home_node doesn't need it because it can just handle the error (EINVAL probably)

Yes, I think it's good, I've modified.

2024-02-01 11:18 UTC, andikleen requested changes
has_home_node should be a tristate to distinguish the case of not supporting home node and the detection not having run yet.

static int has_home_node = -1;

if (has_home_node >= 0)
        goto out;


You have to also modify the ++ to = 1 to make this work. In general I would avoid ++ to set booleans, it is error prone (e.g. could overflow, although not here)



numa_has_node should distinguish the case of has_home_node

2024-02-01 11:43 UTC, luochenglcs commented
> has_home_node should be a tristate to distinguish the case of not supporting home node and the detection not having run yet.
> 
> static int has_home_node = -1;
> 
> if (has_home_node >= 0) goto out;
> 
> You have to also modify the ++ to = 1 to make this work. In general I would avoid ++ to set booleans, it is error prone (e.g. could overflow, although not here)
 
I've modified.
But user must call numa_has_home_node() to get status, so user can't get `the detection not having run yet` status.

2024-02-01 11:48 UTC, luochenglcs commented
Please review again, Thinks.

2024-02-01 12:05 UTC, merged

2024-02-01 12:05 UTC, andikleen commented
Thanks!